### ISSUE TITLE
FC needs a definition of children

### ISSUE THREAD

**Issue by FlowerGeoji** [hirohe/react-watermark#1]
<img width="1448" alt="스크린샷 2022-10-19 오후 4 46 34" src="https://user-images.githubusercontent.com/18716984/196628738-c6601f12-a256-4604-a247-8d394df14244.png">

In React18, `children` type is removed from `React.FC`.

So `WatermarkProps` needs a definition of `children`

**Comment by hirohe** [comment]
thank you for pr

**Comment by hirohe** [comment]
published `0.4.0`
